# Generated by Django 4.1.1 on 2022-09-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=100)),
                ('cust_phone', models.CharField(max_length=10)),
                ('cust_email', models.EmailField(max_length=100)),
                ('cust_remark', models.TextField()),
            ],
        ),
    ]
